### ISSUE TITLE
邮箱发送打卡出现如下错误

### ISSUE THREAD

**Issue by chenzhujin** [georgehuan1994/DingDing-Automatic-Clock-in#11]
![fa46d885ed5aebc0e6af1208fd805e1](https://user-images.githubusercontent.com/67361136/109251368-4f551b00-7826-11eb-8a95-600b33480b51.jpg)

希望老哥解决一下，可以的话，加下本人VX 380485812 不尽感激，送礼答谢****

**Comment by georgehuan1994** [comment]
看下你的脚本，第275行是什么？

**Comment by chenzhujin** [comment]
![8d8a19b755289cdd99fad12286b95bd](https://user-images.githubusercontent.com/67361136/109256122-4f5a1880-7830-11eb-9dd5-97bc2e60a1a3.png)
应该是这部分代码出错了，   btn_sure.click() // 找到 "确定" 按钮，并点击 这句257，会不会是 BUNDLE_ID_DD 包名的问题啊？钉钉版本  V6.0.5

**Comment by chenzhujin** [comment]
调用钉钉，只是调出，那个详细界面，调用不出那个钉钉软件。
![Uploading ee9ce261e3ac2f67a8144dd1b278f9c.jpg…]()

调用到这个界面，没有进入软件。

**Comment by chenzhujin** [comment]
![ee9ce261e3ac2f67a8144dd1b278f9c](https://user-images.githubusercontent.com/67361136/109256613-47e73f00-7831-11eb-83cc-086be8259d5a.jpg)

钉钉软件没有调用出来，每次接收到短信解锁后，就进入到这个界面不动了

**Comment by georgehuan1994** [comment]
有两个问题
1、同时运行了多个脚本。修改脚本之后，记得先在VS Code里按Shift+F5，停止运行脚本；或者在AutoJs里把正在运行的脚本关掉。不然会有很多个进程，而且报错的位置不对，很难定位问题。
2、能打开钉钉的设置界面，说明BUNDLE_ID是正确的，报错的原因可能是没有找到结束运行这个控件，或是点击了结束运行控件但没有找到确认按钮。你先把
```` javascript
let btn_finish = textMatches(/(.*结束.*)|(.*停止.*)|(.*运行.*)/).clickable(true).findOne()
````

改为：
```` javascript
let btn_finish = textMatches("结束运行").clickable(true).findOne()
````
或者
```` javascript
let btn_finish =  descMatches("结束运行").clickable(true).findOne()
````
试一下

**Comment by georgehuan1994** [comment]
替换这个方法在尝试一下，如果还有报错的话再把报错截图和相关代码块发一下

```` javascript
/**
 * @description 结束钉钉进程
 */
function stopApp() {

    console.log("结束钉钉进程")

    // Root
    // shell('am force-stop ' + BUNDLE_ID_DD, true) 

    // No Root
    app.openAppSetting(BUNDLE_ID_DD)
    let btn_finish = textMatches(/(.*结束.*)|(.*停止.*)/).clickable(true).findOne() // 直到找到 "结束运行" 按钮，并点击
    if (btn_finish.enabled()) {
        btn_finish.click()
        console.log("点击了结束按钮")  

        if (null != textMatches("确定").clickable(true).findOne(1000)) { // 点击弹出的对话框中的 "确定" 按钮
            btn_sure = textMatches("确定").clickable(true).findOnce()
            btn_sure.click() 
            console.log("点击了确定按钮")  
        }
        if (null != descMatches("确定").clickable(true).findOne(1000)) {
            btn_sure = textMatches("确定").clickable(true).findOnce()
            btn_sure.click() 
            console.log("点击了确定按钮")  
        }
        console.info(app.getAppName(BUNDLE_ID_DD) + "已被关闭")
    } 
    else {
        console.info(app.getAppName(BUNDLE_ID_DD) + "未在运行")
    }
    sleep(1000)
    home()
    sleep(1000)
}
````

**Comment by chenzhujin** [comment]
现在不会报错，但是应该出现跟第一个同样的问题 《小米获取不到控件名称或者ID #14》  ，一直卡在那个应用详情界面。

**Comment by georgehuan1994** [comment]
代码已更新，移除了 结束钉钉 这个过程

**Comment by chenzhujin** [comment]
在华为荣耀20I 手机中，auto.js 经常会被系统自动关闭。

**Comment by georgehuan1994** [comment]
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
按注意事项里的说明操作一下，看看是否能解决你的问题。
另外你说的无法正常解锁，是指无法点亮屏幕？还是上滑动作无法解锁屏幕？

卡在打卡界面这个问题，可以看看日志，如果是卡在“等待连接到考勤机”，请在脚本开头的常量中修改考勤机名称

**Comment by chenzhujin** [comment]
无上滑，解锁操作，现在可以点击打卡了。只是不能，熄屏解锁。

**Comment by georgehuan1994** [comment]
`swipe(360, 600, 360, 0, 100)`
把解锁方法中的上滑动作改为这个试试

**Comment by chenzhujin** [comment]
![ED053621C6B0F7C73076D7230510BDAF](https://user-images.githubusercontent.com/67361136/110446224-e90baa80-80f9-11eb-9ca3-8c812073bd55.jpg) 显示如图：
![7}JMGX 94GH9FVRH8Q${202](https://user-images.githubusercontent.com/67361136/110446374-10fb0e00-80fa-11eb-8629-5aaf34659308.png)

打开那些都成功了。

**Comment by chenzhujin** [comment]
设备解锁后，是不是也看不到，手机跳转到钉钉界面的啊？我看日记，是有解锁成功的，钉钉也正常的调用起来。但是看手机界面却还是锁屏界面.
