### ISSUE TITLE
多组织不能使用

### ISSUE THREAD

**Issue by hjjcq2017** [georgehuan1994/DingDing-Automatic-Clock-in#12]
楼主，测试了一下，如果加入了多组织，会停止在多组织悬浮选择框处，要手动选择

**Comment by georgehuan1994** [comment]
加上Corp ID试试，看看还需要手动选择吗？

**Comment by hjjcq2017** [comment]
咨询一下，比如下午下班我使用了时间段3:40---4:00在这个期间如何触发自动打卡，打卡时间是随机的吗，我测试了没搞成功

georgehuan1994 <notifications@github.com> 于 2021年3月5日周五 上午8:51写道：

**Comment by georgehuan1994** [comment]
Tasker事件设定为3:40，加一个变量，在0~20分钟内随机，然后再发出通知
