### ISSUE TITLE
关于49行报错的问题，烦请大佬指导

### ISSUE THREAD

**Issue by chouaochieh** [georgehuan1994/DingDing-Automatic-Clock-in#15]
![52941615261509_ pic](https://user-images.githubusercontent.com/80303590/110416816-50f8cb80-80cf-11eb-9827-2da6e21c5dad.jpg)
大佬您好。
第49行报错，这个是什么原因呀？
烦请指导。

**Comment by georgehuan1994** [comment]
看下AutoJs和Android的版本是多少？`console.setGlobalLogConfig(config)` 此方法需要v4.1.0以上版本

**Comment by chouaochieh** [comment]
您好。
谢谢您的回复。
[cid:image001.jpg@01D714EF.19C243E0]
这是我的开发环境。

发件人: georgehuan1994 <notifications@github.com>
答复: georgehuan1994/DingDing-Automatic-Clock-in <reply@reply.github.com>
日期: 2021年3月9日 星期二 12:23
收件人: georgehuan1994/DingDing-Automatic-Clock-in <DingDing-Automatic-Clock-in@noreply.github.com>
抄送: chouaochieh <augus.zhou@gmail.com>, Author <author@noreply.github.com>
主题: Re: [georgehuan1994/DingDing-Automatic-Clock-in] 关于49行报错的问题，烦请大佬指导 (#15)


看下AutoJs和Android的版本是多少？console.setGlobalLogConfig(config) 此方法需要v4.1.0以上版本

―
