### ISSUE TITLE
关于一直卡登陆界面的问题

### ISSUE THREAD

**Issue by zcmk123** [georgehuan1994/DingDing-Automatic-Clock-in#16]
有时候没登录一直在死循环signIn这个函数，是因为et_pwd_login这个获取不到吗，但是钉钉界面确实在登录页，很奇怪。顺便想问下有什么工具可以查看组件id名？我搞前端的，对安卓不是太懂。。。

**Comment by georgehuan1994** [comment]
关于控件的获取，可以参考下这篇文章
https://blog.nowcoder.net/n/57ad50d53a2244daa4ed499d64280b5a

或者看下这个issue
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/5#issuecomment-729338029

**Comment by zcmk123** [comment]
> 关于控件的获取，可以参考下这篇文章
> https://blog.nowcoder.net/n/57ad50d53a2244daa4ed499d64280b5a
> 
> 或者看下这个issue
> [#5 (comment)](https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/5#issuecomment-729338029)

谢谢，我自己调试一下
