### ISSUE TITLE
请教一下，该怎么用呢？

### ISSUE THREAD

**Issue by LuminaK123** [georgehuan1994/DingDing-Automatic-Clock-in#17]
最近公司换了钉钉，我想着来这找找有没有解决之道，就发现了这个。但应该怎么用呢？.js文件好像无法下载，我复制了raw，在auto.js里新建了文件然后粘贴进去，运行报错。有点迷茫啊，纯粹的新手小白，希望您能给个教程或简单说一下应该怎么做

**Comment by df13954** [comment]
> 最近公司换了钉钉，我想着来这找找有没有解决之道，就发现了这个。但应该怎么用呢？.js文件好像无法下载，我复制了raw，在auto.js里新建了文件然后粘贴进去，运行报错。有点迷茫啊，纯粹的新手小白，希望您能给个教程或简单说一下应该怎么做

我也是小白，这个怎么用的呢
