### ISSUE TITLE
请问这些位置参数  是按某个具体手机来设置的吗 ？ 

### ISSUE THREAD

**Issue by onepow** [georgehuan1994/DingDing-Automatic-Clock-in#2]
![图片](https://user-images.githubusercontent.com/20081543/98760293-f47dec00-240d-11eb-83bc-e5f6d0873406.png)

谢谢作者的分享， 脚本测试运行在PAD上 发现点击打卡时没有打到， 不同设备要要根据 实际尺寸调整吧  ？

**Comment by georgehuan1994** [comment]
可以适配不同分辨率。

1、关于Home键坐标。用途是：利用手机的快捷手势（长按Home键锁屏）进行锁屏操作；已Root的设备可以直接使用`Power()`函数来锁屏。
2、关于打卡按钮坐标。在实测中，上班打卡按钮有可能会获取不到，所以使用了坐标操作。可以在调用位置后加个判断：
```javascript
    if (null != textMatches("上班打卡").clickable(true).findOne(1000)) {
        textMatches(/(.*上班打卡.*)/).findOnce().click()
        console.log("按下打卡按钮")
        sleep(1000)
    }
```

**Comment by georgehuan1994** [comment]
如果还是不行的话，可以打开极速打卡功能，这样就能在钉钉启动时打卡

**Comment by onepow** [comment]
![图片](https://user-images.githubusercontent.com/20081543/98791985-c8c82980-2440-11eb-9a3a-9ca1dc7db10b.png)

谢谢， 我也觉得直接通过 文本 来获取打卡按钮会好使一点， 实测 华为BTV 平板  用坐标定位的方式上下班打卡 定不准，你初使的坐标位置  x : 540 , y: 1325   不能正确点击按钮 ，

**Comment by onepow** [comment]
我看 下班打卡的 位置获取就用  文本名称 ， 测试是可行的  。
![图片](https://user-images.githubusercontent.com/20081543/98792453-7dfae180-2441-11eb-90b0-e0b330409e0a.png)

**Comment by georgehuan1994** [comment]
“下班打卡”可以获取到，不过“上班打卡”有时会失效
