### ISSUE TITLE
进入考勤页面 未成功打卡

### ISSUE THREAD

**Issue by lruri** [georgehuan1994/DingDing-Automatic-Clock-in#20]
完全不懂技术的新人求问
根据tasker设定的定时提醒  
设备定时唤醒
随机时间后启动钉钉
一段时间后打开考勤页面
之后再考勤页面  没有点击上班/下班打卡
之后屏幕关闭

看日记显示有操作下班打卡  但实际未点击下班
这个地方是缺少什么操作吗
还是需要调试页面打卡位置坐标（看页面说明是根据窗口句柄）

![WechatIMG103](https://user-images.githubusercontent.com/2189461/113796947-e34dc700-9782-11eb-88df-977bdeae2111.jpeg)

**Comment by lruri** [comment]
已开启极速打卡

**Comment by georgehuan1994** [comment]
```` javaScript
if (null != textContains("休息").findOne(1000) || null != descContains("休息").findOne(1000)) {
        console.info("今日休息")
        home()
        sleep(1000)
        return;
    }
````
看日志，是执行到这句的时候，直接跳出了整个方法。
但又没有报错，很奇怪！
我个人猜测，原因可能跟华为系统设定有关，导致两个UiSelector的或判断出了问题。
麻烦你，把上面这段代码，从 “上班打卡” 和 “下班打卡” 这两个方法中注释掉，再测试一下。

**Comment by lruri** [comment]
> ```js
> if (null != textContains("休息").findOne(1000) || null != descContains("休息").findOne(1000)) {
>         console.info("今日休息")
>         home()
>         sleep(1000)
>         return;
>     }
> ```
> 
> 看日志，是执行到这句的时候，直接跳出了整个方法。
> 但又没有报错，很奇怪！
> 我个人猜测，原因可能跟华为系统设定有关，导致两个UiSelector的或判断出了问题。
> 麻烦你，把上面这段代码，从 “上班打卡” 和 “下班打卡” 这两个方法中注释掉，再测试一下。



> ```js
> if (null != textContains("休息").findOne(1000) || null != descContains("休息").findOne(1000)) {
>         console.info("今日休息")
>         home()
>         sleep(1000)
>         return;
>     }
> ```
> 
> 看日志，是执行到这句的时候，直接跳出了整个方法。
> 但又没有报错，很奇怪！
> 我个人猜测，原因可能跟华为系统设定有关，导致两个UiSelector的或判断出了问题。
> 麻烦你，把上面这段代码，从 “上班打卡” 和 “下班打卡” 这两个方法中注释掉，再测试一下。

刚试了一下 注释掉这段代码
依然没有成功，截图给您，麻烦您帮忙看下，麻烦啦（另外我看屏幕上点击打卡的位置好像不是在屏幕高度0.56位置，好像偏下一点  我改成0.44依然没有成功）
![1](https://user-images.githubusercontent.com/2189461/113858812-bfb46c00-97d6-11eb-916b-df8ce2aa8b7b.jpeg)
![2](https://user-images.githubusercontent.com/2189461/113858824-c2af5c80-97d6-11eb-9f4f-069ef204ec66.jpeg)
![3](https://user-images.githubusercontent.com/2189461/113858829-c347f300-97d6-11eb-9db4-e5b967d1d7ac.jpeg)

**Comment by georgehuan1994** [comment]
早上那个问题是OK了，注释掉之后，完整执行了 “下班打卡” 方法。
没有点击打卡按钮，是因为 下班打卡这个方法里，是通过查找 下班打卡 这4个字来锁定按钮的，找不就不会点

**Comment by lruri** [comment]
> 早上那个问题是OK了，注释掉之后，完整执行了 “下班打卡” 方法。
> 没有点击打卡按钮，是因为 下班打卡这个方法里，是通过查找 下班打卡 这4个字来锁定按钮的，找不就不会点

还想问下 完整执行了 下班打卡的方法，页面上也有下班打卡字样，为何没有点击到，请问还需要如何调试呢

**Comment by georgehuan1994** [comment]
关于控件的获取，可以参考下这篇文章
https://blog.nowcoder.net/n/57ad50d53a2244daa4ed499d64280b5a

或者看下这个issue
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/5#issuecomment-729338029
