### ISSUE TITLE
增加qq消息获取打卡

### ISSUE THREAD

**Issue by ClownDi** [georgehuan1994/DingDing-Automatic-Clock-in#21]
const BUNDLE_ID_QQ = "com.tencent.mobileqq"

**Comment by ClownDi** [comment]
bundleId == BUNDLE_ID_MAIL || bundleId == BUNDLE_ID_XMSF || bundleId == BUNDLE_ID_QQ

**Comment by ClownDi** [comment]
function SendMessage(title, message) {
    console.log("开始发送消息流程！")
    console.log("打开应用")
    app.startActivity({
        data:"mqqwpa://im/chat?chat_type=wpa&uin="+接收消息的qq号码,
    });
    sleep(500);
    id("input").setText(title+message);
    sleep(500);
    while(!click("发送"));
    sleep(500);
    console.log("正在发送消息...")
    home()
    sleep(1000)
}

**Comment by ClownDi** [comment]
因为工程机邮箱大师不会弹出通知，改成QQ接收和发送消息，感谢作者大佬分享

**Comment by amaztony** [comment]
QQ方便很多，邮箱大师会合并通知不友好，而且新邮件提醒有延迟。
发消息用QQ也稳定许多，打开QQ时通知提醒也自动清除了，很舒服。
我还自己加了个日志读取，方便远程排查问题。
感谢。
