### ISSUE TITLE
钉钉开启了极速打卡，未监听考勤结果

### ISSUE THREAD

**Issue by ZionNuption** [georgehuan1994/DingDing-Automatic-Clock-in#24]
钉钉开启了极速打卡，未监听考勤结果，不知道是不是这个监听文本的事，因为难以测试，还请大佬赐教。
![image](https://user-images.githubusercontent.com/23336931/118623293-adc4e080-b7fa-11eb-8296-399f48ebe1ed.png)
![image](https://user-images.githubusercontent.com/23336931/118623316-b5848500-b7fa-11eb-8c68-8669ceeed871.png)

**Comment by georgehuan1994** [comment]
看看日志，有没有收到通知，通知内容是什么

**Comment by ZionNuption** [comment]
没有收到钉钉考勤结果的通知，日志没看到对应信息，看代码本来是执行完打卡立刻锁屏的，以为是钉钉没来得及发送结果通知，停了10秒
![image](https://user-images.githubusercontent.com/23336931/118746541-0479fb00-b88b-11eb-98cc-fd6b410d552b.png)
也没啥用
感觉钉钉发的是这个把
![image](https://user-images.githubusercontent.com/23336931/118746657-31c6a900-b88b-11eb-8ec4-3c8c0ad8649f.png)

**Comment by georgehuan1994** [comment]
这是你自己加的吧，我的示例代码里，并没有这一句。
请关闭通知过滤器，如果还是没有收到任何来自钉钉的通知，那么有可能是钉钉的通知权限没有打开，或钉钉的通知是通过系统的推送服务发出的。

**Comment by georgehuan1994** [comment]
请注意保护自己的隐私，上传包含个人相关信息的截图之前，进行脱敏处理

**Comment by ZionNuption** [comment]
> 这是你自己加的吧，我的示例代码里，并没有这一句。
> 请关闭通知过滤器，如果还是没有收到任何来自钉钉的通知，那么有可能是钉钉的通知权限没有打开，或钉钉的通知是通过系统的推送服务发出的。

休眠10秒是我加的，以为是老机子太卡，没来得及处理。钉钉通知是开了的，就是看日志感觉打卡成功后没有发通知，或者代码监听的内容不对。

**Comment by ZionNuption** [comment]
> 请注意保护自己的隐私，上传包含个人相关信息的截图之前，进行脱敏处理

好的，截图没有泄漏敏感信息~~哈哈

**Comment by ZionNuption** [comment]
![image](https://user-images.githubusercontent.com/23336931/118748757-deeef080-b88e-11eb-88e3-863426e5e733.png)
![image](https://user-images.githubusercontent.com/23336931/118748778-e615fe80-b88e-11eb-9877-a67100b8d5db.png)
还加了下下班区间的判断，因为测试的时候一不小心就打了早退卡

**Comment by georgehuan1994** [comment]
![image](https://user-images.githubusercontent.com/49583943/118749099-718f8f80-b88f-11eb-9762-2dcf386c3538.png)
把消息免打扰关了

**Comment by ZionNuption** [comment]
> ![image](https://user-images.githubusercontent.com/49583943/118749099-718f8f80-b88f-11eb-9762-2dcf386c3538.png)
> 把消息免打扰关了
好的，应该是这个了，看到你的打码明白了。马上删除发言

**Comment by ZionNuption** [comment]
大佬把图也藏了把··

**Comment by ZionNuption** [comment]
好的，明白大佬意思了，麻烦大佬把那个图也删了把~~
