### ISSUE TITLE
Thread[ScriptThread-1[[remote]DingDing-Automatic-Clock-in.js] (Spawn-6),5]: ReferenceError: "PACKAGE_NAME_DD" is not defined. ([remote]DingDing-Automatic-Clock-in.js#352)

### ISSUE THREAD

**Issue by echoowall** [georgehuan1994/DingDing-Automatic-Clock-in#26]
[Extension Host] 01:25:40.094/D: 唤醒设备
workbench.desktop.main.js:62 [Extension Host] 01:25:40.106/I: 设备已唤醒
workbench.desktop.main.js:62 [Extension Host] 01:25:40.114/I: 设备已唤醒
workbench.desktop.main.js:62 [Extension Host] 01:25:42.115/D: 解锁屏幕
workbench.desktop.main.js:62 [Extension Host] 01:25:42.120/D: 解锁屏幕
workbench.desktop.main.js:62 [Extension Host] 01:25:44.169/I: 屏幕已解锁
workbench.desktop.main.js:62 [Extension Host] 01:25:44.198/E: Thread[ScriptThread-1[[remote]DingDing-Automatic-Clock-in.js] (Spawn-6),5]: ReferenceError: "PACKAGE_NAME_DD" is not defined. ([remote]DingDing-Automatic-Clock-in.js#352)ReferenceError: "PACKAGE_NAME_DD" is not defined.    at signIn ([remote]DingDing-Automatic-Clock-in.js:352:0)    at doClock ([remote]DingDing-Automatic-Clock-in.js:196:0)    at [remote]DingDing-Automatic-Clock-in.js:123:0 
workbench.desktop.main.js:62 [Extension Host] 01:25:44.493/I: 屏幕已解锁
workbench.desktop.main.js:62 [Extension Host] 01:25:44.501/E: Thread[ScriptThread-3[[remote]DingDing-Automatic-Clock-in.js] (Spawn-4),5]: ReferenceError: "PACKAGE_NAME_DD" is not defined. ([remote]DingDing-Automatic-Clock-in.js#352)ReferenceError: "PACKAGE_NAME_DD" is not defined.    at signIn ([remote]DingDing-Automatic-Clock-in.js:352:0)    at doClock ([remote]DingDing-Automatic-Clock-in.js:196:0)    at [remote]DingDing-Automatic-Clock-in.js:123:0

这是啥原因··
小米5 MIUI10

**Comment by echoowall** [comment]
![image](https://user-images.githubusercontent.com/7361042/120114097-1a9f8980-c1b0-11eb-9a12-c67e063db357.png)
这是352行

**Comment by georgehuan1994** [comment]
把所有的PACKAGE_NAME_DD，替换成PACKAGE_ID_DD
