### ISSUE TITLE
关于远程打卡

### ISSUE THREAD

**Issue by onepow** [georgehuan1994/DingDing-Automatic-Clock-in#3]
![图片](https://user-images.githubusercontent.com/20081543/98793763-4c831580-2443-11eb-864b-f9879143ac12.png)

![图片](https://user-images.githubusercontent.com/20081543/98793781-5278f680-2443-11eb-9299-d250665dbc8d.png)

我理解的原理 是，  tasker 定期发 特定文本的 通知 ，  由auto.js  监听捕获特定通知 ， 然后执行JS脚本进行打卡，

非常好的思路， 我想问下远程打卡， 发邮件是指发送到绑定 网易邮箱大师的邮件吗， 发送邮件后似乎不能发出相应的 打卡通知 ？

**Comment by georgehuan1994** [comment]
根据通知的包名、摘要、文本来判断，任何通讯应用都可以，不一定要使用邮件。
收不到邮件回复，可能是没有通过邮件应用发出通知，而是通过手机厂商的推送服务发出了通知

**Comment by onepow** [comment]
谢谢，有一个新问题是 ，休眠后不能自动唤醒，  TASKER 不能通知唤醒 ， Auto.js 也不能执行，  人工解锁打开后才能执行 ？？

**Comment by georgehuan1994** [comment]
设置为通知亮屏试试
