### ISSUE TITLE
事先没有排版的，没办法实现“快速打卡”去？

### ISSUE THREAD

**Issue by JJwater** [georgehuan1994/DingDing-Automatic-Clock-in#32]
能不能设置成，一天8个小时内打4次？

**Comment by JJwater** [comment]
tester定时打卡，能把随机事件缩短吗

**Comment by georgehuan1994** [comment]
你可以在 tasker 中配置多个任务。随机时间是在js脚本中定义的，你可以修改第22、23行的 `LOWER_BOUND` 和 `UPPER_BOUND`
```javascript
const LOWER_BOUND = 1 * 60 * 1000 // 最小等待时间：1min
const UPPER_BOUND = 5 * 60 * 1000 // 最大等待时间：5min
```

**Comment by JJwater** [comment]
> 任务处理器随机时间是在js脚本中定义的，你可以修改第22、23行的 和`LOWER_BOUND``UPPER_BOUND`
> 
> ```js
> const LOWER_BOUND = 1 * 60 * 1000 // 最小等待时间：1min
> const UPPER_BOUND = 5 * 60 * 1000 // 最大等待时间：5min
> ```

拜你为师好不好
