### ISSUE TITLE
卡在钉钉页面，不进行打卡

### ISSUE THREAD

**Issue by SkyHunterC** [georgehuan1994/DingDing-Automatic-Clock-in#33]
![QQ图片20210915181146](https://user-images.githubusercontent.com/41264239/133415219-7efc2f95-caf9-4a69-8e9c-dd52fe41f131.jpg)
![微信图片_打卡](https://user-images.githubusercontent.com/41264239/133415255-ba5a9391-99f4-465b-b04f-50cff451e8d6.jpg)

**Comment by SkyHunterC** [comment]
大佬，帮忙看看是什么问题，感谢

**Comment by georgehuan1994** [comment]
脚本文件发一下，你用的脚本是从这个仓库下载的吗？看日志打印，堆栈的方法名很奇怪，感觉不是我写的

**Comment by SkyHunterC** [comment]
> 脚本文件发一下，你用的脚本是从这个集中下载的吗？看日志，方法的方法名很相似，感觉不是我写的

[DingDing-Automatic-Clock-in.txt](https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/files/7174184/DingDing-Automatic-Clock-in.txt)
是从这下载的

**Comment by georgehuan1994** [comment]
是同时运行了其他的脚本吗？6137391d166cdd8003cbc066.js 这个脚本是什么？
日志中的报错应该不是从 DingDing-Automatic-Clock-in.js 中发出的

**Comment by SkyHunterC** [comment]
> 6137391d166cdd8003cbc066

没别的脚本了啊，我今天再试试

**Comment by SkyHunterC** [comment]
> 看下这条报错的前几条日志

![QQ图片20211009180712](https://user-images.githubusercontent.com/41264239/136653895-1188a45a-affb-42b4-8357-bad90fa6ce60.jpg)

**Comment by SkyHunterC** [comment]
> 看下这条报错的前几条日志

![QQ图片20211009181024](https://user-images.githubusercontent.com/41264239/136653972-aee3b0a0-6633-4cfc-aa96-17b24725c1d2.jpg)

**Comment by SkyHunterC** [comment]
> 按照下面修改 `notificationHandler()` 方法
> 
> ```js
> /**
>  * @description 处理监听到的通知
>  * @param {notification} n 通知对象
>  */
> function notificationHandler(n) {
>  
>     .....
> 
>     if (text == null) 
>     return;
> 
>     // 加上这个判断 
>     if (text.length <= 2) {
>         return;
>     }
>     
>     // 监听钉钉返回的考勤结果
>     if (packageId == PACKAGE_ID_DD && text.indexOf("考勤打卡") >= 0) { 
>         setStorageData("dingding", "clockResult", text)
>         threads.shutDownAll()
>         threads.start(function(){
>             // sendQQMsg(text)
>             systemCamerashot()
>             sendEmail("考勤结果", text, cameraFilePath)
>         })
>         return;
>     }
> }
> ```

大佬啊，还是没用，不过我发现一个规律就是，PC登录钉钉就会出现这个错误，最近我发现脚本结束时间都是我在PC登录的时候，不登录PC钉钉就没事

**Comment by georgehuan1994** [comment]
[DDAC-debug.txt](https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/files/7479842/DDAC-debug.txt)
把所有运行的脚本关闭，重启设备，然后运行这个脚本，记得重新配置一下脚本里的常量。再尝试登录PC钉钉看看能不能复现

**Comment by SkyHunterC** [comment]
> [DDAC-debug.txt](https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/files/7479842/DDAC-debug.txt) 把所有运行的脚本关闭，重启设备，然后运行这个脚本，记得重新配置一下脚本里的常量。再尝试登录PC钉钉看看能不能复现

换了debug后这个错误再没出现过。。。
