### ISSUE TITLE
自己改了点但js代码改动不多所以没有pr，算是一种备选方案的思路

### ISSUE THREAD

**Issue by Aroad233** [georgehuan1994/DingDing-Automatic-Clock-in#40]
为了轻量化，结合了server酱的pushdeer

发送http请求 push通知到打卡机

而后将http请求封装到类似于iphone快捷指令或者安卓其他的快捷指令

一键完成试了下很爽

**Comment by wekingchen** [comment]
大大分享一下嘛

**Comment by ckqqqq** [comment]
大大能分享一下吗

**Comment by Aroad233** [comment]
> 大大分享一下嘛

https://sct.ftqq.com/

SERVE酱注册后下载安卓版的pushdeer
然后把pushdeer 对应的包路径扔到js的信任名单里面，有个数组
然后pushdeer常开 小米的手机写了米push 可以不用常开
而后只需要在一定时间内发送http请求到pushdeer的指定路径就行了

**Comment by Aroad233** [comment]
> 大大能分享一下吗

见楼上

**Comment by ckqqqq** [comment]
谢谢！我研究一下。
