### ISSUE TITLE
息屏后无法打开钉钉

### ISSUE THREAD

**Issue by Angelyeye** [georgehuan1994/DingDing-Automatic-Clock-in#41]
息屏后无法打开钉钉，直接返回主屏幕，但是在auto.js界面就可以直接打开钉钉

**Comment by georgehuan1994** [comment]
发下日志

**Comment by Angelyeye** [comment]
![1D63D5B43F70D092FF3357573B1A87B9](https://user-images.githubusercontent.com/58071062/160533478-eb692608-2c1c-443b-9c66-ad5a2142a44b.jpg)

**Comment by Angelyeye** [comment]
实际上并没有启动钉钉界面，而是直接返回主屏幕就没动了

**Comment by georgehuan1994** [comment]
你同时运行了多个脚本，关掉多余的再试试
