### ISSUE TITLE
CORP_ID因为智能助理关闭，还有什么方法获取嘛？

### ISSUE THREAD

**Issue by ZZtac** [georgehuan1994/DingDing-Automatic-Clock-in#42]
111

**Comment by georgehuan1994** [comment]
PC钉钉侧边栏 -> 工作台 -> OA审批 -> 请假

跟组织相关的链接都会包含 corpid，没有请假的话找找其他的

![image](https://user-images.githubusercontent.com/49583943/161913953-b4177725-37c0-400f-a1ad-d45a87a00813.png)

**Comment by ZZtac** [comment]
谢谢
