### ISSUE TITLE
发送邮件时提示未获取权限

### ISSUE THREAD

**Issue by ukipoi** [georgehuan1994/DingDing-Automatic-Clock-in#43]
把程序停留在应用选择界面，自己打开网易邮箱大师。
也是没权限上传不了附件

但是如果选择其他应用，比如钉钉又是可以把文件发送出去的。

而且从文件管理器手动分享文件，用网易邮箱大师也能发出去。

好怪

**Comment by georgehuan1994** [comment]
网易邮箱大师添加附件比较麻烦，一般手机都会自带一个邮件应用，可以考虑使用内置邮件应用来发送，或者使用其他方式
