### ISSUE TITLE
自动登录问题：无法勾选隐私协议

### ISSUE THREAD

**Issue by somuc** [georgehuan1994/DingDing-Automatic-Clock-in#44]
cb_privacy是这个id错误吗？

**Comment by georgehuan1994** [comment]
6.5.0 版本仍然是这个 id

**Comment by somuc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯谢谢 可以了，是元素没加载出来的问题。做了一点延迟就可以了。另外，有没有“更新打卡”的操作？
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                974201083
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年5月25日 10:55，George ***@***.***> 写道： 




6.5.0 版本仍然是这个 id



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by somuc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    更新打卡弄出来了，照着写就可以了 }    if (null != textMatches("更新打卡").clickable(true).findOne(10000)) {        textMatches("更新打卡").clickable(true).findOnce().click()        console.log("按下更新打卡")        sleep(3000)        if (null != textMatches("确定").clickable(true).findOne(10000)) {            textMatches("确定").clickable(true).findOnce().click()            console.log("确定")            sleep(3000)        }    }
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                974201083
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年5月25日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯谢谢 可以了，是元素没加载出来的问题。做了一点延迟就可以了。另外，有没有“更新打卡”的操作？
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                974201083
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年5月25日 10:55，George ***@***.***> 写道： 




6.5.0 版本仍然是这个 id



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
