### ISSUE TITLE
在auto.js中运行脚本报错。顺便咨询下使用auto.js自带的定时计划是否可以取代tasker呢？

### ISSUE THREAD

**Issue by cukewu** [georgehuan1994/DingDing-Automatic-Clock-in#46]
![1](https://user-images.githubusercontent.com/18632013/173494034-db91efde-d1b9-4281-bcad-44d3a48dfb9f.jpg)

在auto.js中运行脚本报错。顺便咨询下使用auto.js自带的定时计划是否可以取代tasker呢？

**Comment by georgehuan1994** [comment]
#9

**Comment by georgehuan1994** [comment]
如果你的设备不息屏的话，可以使用autojs自带的定时器

**Comment by cukewu** [comment]
好的，非常感谢。
提个小建议哈哈，
https://github.com/TonyJiangWJ/AutoScriptBase
之前我用的这个网友的自动收支付宝能量的Auto.js脚本可以定时自动唤醒屏幕并且解锁，我试试看能否合并下两个代码
