### ISSUE TITLE
点击打卡按钮无效，是不是和手机屏幕分辨率有关系？

### ISSUE THREAD

**Issue by cukewu** [georgehuan1994/DingDing-Automatic-Clock-in#47]
请问下，我发现在执行click(device.width / 2, device.height * 0.560) 的时候感觉程序没点到那个打卡的按钮。怀疑是不是因为分辨率的关系实际点的是旁边的空白地方，不是打卡的按钮上。我应该如何得到这个打卡按钮的实际坐标并且写入程序中呢？ 类似这种click(1440,900)？

**Comment by georgehuan1994** [comment]
设备进入开发者模式后，在开发者选项里面，有一个【Pointer Location】指针位置，打开它
