### ISSUE TITLE
如何运行 auto js 的 调用 邮件发送列表时 获取该 弹窗及其里面的元素 ？ 

### ISSUE THREAD

**Issue by onepow** [georgehuan1994/DingDing-Automatic-Clock-in#5]
如题 ，你好，现在这个邮件发送的问题一直困扰我， 

即在这段代码  
app.sendEmail({
        email: [EMAILL_ADDRESS],
        subject: "考勤结果",
        text: message
    })  

后 弹窗了 邮件发送应用列表 窗体， 我该如何 获取访窗口及其里面的应用 呢 ？
 
我想用   FloatyWindow.{id}  的方式获取 ‘网易邮箱大师’ 然后模拟点击，

![图片](https://user-images.githubusercontent.com/20081543/99380317-c06e6380-2904-11eb-943b-b8c8826f19d9.png)

现在问题是这个窗口句柄 及 窗口上的 应用名称 id 该 如何 获取 ，请赐教， 谢谢。

**Comment by onepow** [comment]
![Uploading 图片.png…]()

**Comment by onepow** [comment]
![图片](https://user-images.githubusercontent.com/20081543/99380725-48546d80-2905-11eb-8520-bfaebd7e4022.png)

**Comment by georgehuan1994** [comment]
![image](https://user-images.githubusercontent.com/49583943/99475305-40d6a800-2989-11eb-86bb-79176c80ec26.png)
![image](https://user-images.githubusercontent.com/49583943/99475316-446a2f00-2989-11eb-868b-5f17b5cf6c31.png)
![image](https://user-images.githubusercontent.com/49583943/99475352-55b33b80-2989-11eb-81dd-77f02913ddf7.png)
![image](https://user-images.githubusercontent.com/49583943/99475567-c3f7fe00-2989-11eb-8291-662f1feed490.png)
使用AutoJs自带的工具查看相关属性、生成代码

**Comment by onepow** [comment]
非常感谢 ! Many many thx !

**Comment by onepow** [comment]
![图片](https://user-images.githubusercontent.com/20081543/99908176-0cae0f00-2d1c-11eb-81ca-027a3d18e316.png)

当我试图 用  ‘布局分析 ’   时，当打开时  邮件应用列表弹窗就关闭了， 所以无法定位到 弹窗的邮箱大师，
请问题 这种情况怎么解决， 我看你的截图是有成功截到 弹窗列表中 邮箱大师的，谢谢。 

![Uploading share.jpg…]()

**Comment by onepow** [comment]
![图片](https://user-images.githubusercontent.com/20081543/99908450-b80b9380-2d1d-11eb-95e4-8ff2a5e9839d.png)

**Comment by georgehuan1994** [comment]
AutoJs Pro 8.5.21市场版 修复了这个问题，可以试试
修复 打包时闪退问题（已知问题：Android11上原生界面打包和运行有报错
修复 自定义符号编辑后无效的问题
修复 华为系统悬浮窗跳通知管理问题
