### ISSUE TITLE
想请教下作者是否可以集成安卓4位数字解锁和钉钉极速打卡的功能

### ISSUE THREAD

**Issue by cukewu** [georgehuan1994/DingDing-Automatic-Clock-in#52]
请教下作者，
1.一个需求是安卓4位数字密码解锁（其他auto.js已经实现，但是要把代码迁移合并过来）
2.目前作者的版本应该是依靠监听关键字来启动钉钉的，是不是可以有一个简化版，定时启动钉钉即可，因为只是极速打卡功能

作者方便给邮箱或者wechat么，方便沟通些

**Comment by georgehuan1994** [comment]
1. 锁屏密码可以参考: https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/35#issuecomment-940566141
2. 监听的目的只是在某个时间唤醒屏幕，但不能只依靠 autojs 中的定时，或自己的 sleep 定时，不可靠。需要依靠系统级的服务。
