### ISSUE TITLE
无法自动登录

### ISSUE THREAD

**Issue by mywinr** [georgehuan1994/DingDing-Automatic-Clock-in#54]
钉钉登录界面可以输入账号，但无法输入密码。第一次遇到这个问题，之前用其他手机不会有这个问题特来请教。

**Comment by georgehuan1994** [comment]
猜测是 系统 或 输入法，开启了某种安全防护功能。也有可能是软键盘劫持，输入了，但少一次回车

**Comment by quqinyuni** [comment]
```
if (id("et_phone_input").exists() && id("et_pwd_login").exists()) {
            id("et_phone_input").findOne().setText(ACCOUNT);
            sleep(1000);
            id("et_pwd_login").findOne().setText(PASSWORD);
            console.log("使用ID选择输入");
        } else {
            setText(0, ACCOUNT);
            sleep(1000);
            setText(1, PASSWORD);
            console.log("使用setText输入");
        }

        // var account = id("et_phone_input").findOne()
        // account.setText(ACCOUNT)
        // toastLog("输入账号")
        // sleep(3000)
        // shell("input keyevent 66", true)
        // var password = id("et_pwd_login").findOne()
        // toastLog(password)
        // password.setText(PASSWORD)
        // toastLog("输入密码")
        // sleep(3000)
        var privacy = id("cb_privacy").findOne()
        privacy.click()
        toastLog("同意隐私协议")

        var btn_login = id("btn_next").findOne()
        btn_login.click()
        console.log("正在登陆...")
```
登录那块我调整成这样了,你可以试试

**Comment by qq532955362** [comment]
我是直接换成了先全部输入框输入一遍密码，然后等一秒，账号框输入账号

**Comment by cukewu** [comment]
没太明白这段代码的含义
else {
            setText(0, ACCOUNT);
            sleep(1000);
            setText(1, PASSWORD);
            console.log("使用setText输入");

**Comment by Jayce-Jackson** [comment]
> ```
> if (id("et_phone_input").exists() && id("et_pwd_login").exists()) {
>             id("et_phone_input").findOne().setText(ACCOUNT);
>             sleep(1000);
>             id("et_pwd_login").findOne().setText(PASSWORD);
>             console.log("使用ID选择输入");
>         } else {
>             setText(0, ACCOUNT);
>             sleep(1000);
>             setText(1, PASSWORD);
>             console.log("使用setText输入");
>         }
> 
>         // var account = id("et_phone_input").findOne()
>         // account.setText(ACCOUNT)
>         // toastLog("输入账号")
>         // sleep(3000)
>         // shell("input keyevent 66", true)
>         // var password = id("et_pwd_login").findOne()
>         // toastLog(password)
>         // password.setText(PASSWORD)
>         // toastLog("输入密码")
>         // sleep(3000)
>         var privacy = id("cb_privacy").findOne()
>         privacy.click()
>         toastLog("同意隐私协议")
> 
>         var btn_login = id("btn_next").findOne()
>         btn_login.click()
>         console.log("正在登陆...")
> ```
> 
> 登录那块我调整成这样了,你可以试试

感谢大佬，完美解决

**Comment by ssyRo156** [comment]
https://www.pgyer.com/ddex 用这个, 神器

**Comment by georgehuan1994** [comment]
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/54#issuecomment-1324664274
