### ISSUE TITLE
能点亮屏幕，但是无法进入桌面，这个是什么问题oppo A7x

### ISSUE THREAD

**Issue by hylsay** [georgehuan1994/DingDing-Automatic-Clock-in#56]
能点亮屏幕，但是无法进入桌面，这个是什么问题oppo A7x

**Comment by hylsay** [comment]
![ed56a0e905e117fc69d4043dec8ce7db](https://user-images.githubusercontent.com/33367747/215312969-1edd218a-e584-46a9-a641-94aec99f22f8.jpg)

**Comment by hylsay** [comment]
点亮后就停在这里

**Comment by georgehuan1994** [comment]
可能是上滑解锁失败了，查看下日志，看看有没有打印 “解锁成功” 的消息。

**Comment by hylsay** [comment]
> 可能是上滑解锁失败了，查看下日志，看看有没有打印 “解锁成功” 的消息。

谢谢，问题解决了额，是因为qq通知消息锁屏了，划不动
