### ISSUE TITLE
请问在华为手机里能正常运行，但是放到vivo手机里面就提示“错误：length=3;index=8”

### ISSUE THREAD

**Issue by tiger12138tiger** [georgehuan1994/DingDing-Automatic-Clock-in#65]
请问在华为手机里能正常运行，但是放到vivo手机里面就提示“错误：length=3;index=8”

**Comment by jessicasome** [comment]
同样问题

**Comment by jessicasome** [comment]
已解决，原因是只要按底部回到主屏幕的按钮就直接退出了脚本。
不报错的方法是使用悬浮按钮退出，效果为使程序挂起而不是直接退出

**Comment by ssyRo156** [comment]
https://www.pgyer.com/ddex 用这个, 神器

**Comment by LEggcookies** [comment]
> https://www.pgyer.com/ddex 用这个, 神器

👍🏻
请问有使用说明么

**Comment by georgehuan1994** [comment]
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/65#issuecomment-1621913557
