### ISSUE TITLE
大神你好，单位禁用了极速打卡，请问这个方法还能用吗？谢谢

### ISSUE THREAD

**Issue by dff-10026** [georgehuan1994/DingDing-Automatic-Clock-in#7]
大神你好，单位禁用了极速打卡，请问这个方法还能用吗？谢谢。VX:18660930615方便加下微信吗？

**Comment by georgehuan1994** [comment]
可以，极速打卡不是必须的。有问题在git上回复就行

**Comment by dff-10026** [comment]
好的，我想弄钉钉虚拟打卡，但是我不懂脚本啊，想请教大神要怎么做才能打卡，还有钉钉打卡要人脸识别，不知道可以不？请赐教，谢谢。

**Comment by georgehuan1994** [comment]
这个脚本只支持蓝牙考勤机噢。生物识别还没有什么解决办法，只能破解钉钉的协议，或者是破解考勤机。

**Comment by dff-10026** [comment]
我这公司蓝牙考勤也得人脸识别，哎

**Comment by dff-10026** [comment]
嗯，谢谢，如果可以的话麻烦告知一下。
