### ISSUE TITLE
外勤，备注

### ISSUE THREAD

**Issue by mmuuyyuu** [georgehuan1994/DingDing-Automatic-Clock-in#8]
你好，请问外勤打卡怎么搞，加上填写备注。
刚接触，不懂怎么找到这两个按钮。

**Comment by georgehuan1994** [comment]
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/5#issuecomment-729338029
可以参考这个issue。找到对应的控件，调整 "上班打卡" 和 "下班打卡" 这两个过程就可以了

**Comment by georgehuan1994** [comment]
如果不用连接考勤机的话，弄个虚拟定位就可以了呀

**Comment by mmuuyyuu** [comment]
更改手机定位，会不会被检测到？

**Comment by mmuuyyuu** [comment]
嗯，好的。如果仿照‘上班打卡’这操作应该可以，我是想问清楚。具体的元素ID你这边是怎么得到的。例如 登录下一步按钮 I元素ID “btn_next”

**Comment by georgehuan1994** [comment]
https://github.com/georgehuan1994/DingDing-Automatic-Clock-in/issues/5#issuecomment-729338029
可以参考这个issue。

**Comment by mmuuyyuu** [comment]
嗯，懂了。谢谢
